# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${env:ORG}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: grupprojekt
# "service" is the name of this project. This will also be added to your AWS resource names.
service: hotell-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${env:ROLE}

functions:
  CreateReservation:
    handler: functions/CreateReservation/index.handler
    events:
      - httpApi:
          path: /reservation
          method: POST

  CreateRooms:
    handler: functions/CreateRooms/index.handler
    events:
      - httpApi:
          path: /create
          method: POST

  DeleteBooking:
    handler: functions/DeleteReservation/index.handler
    events:
      - httpApi:
          path: /reservation/{id}
          method: DELETE

  GetAllRooms:
    handler: functions/GetAllRooms/index.handler
    events:
      - httpApi:
          path: /rooms
          method: GET

  GetAllReservations:
    handler: functions/GetAllReservations/index.handler
    events:
      - httpApi:
          path: /reservation
          method: GET
  UpdateReservation:
    handler: functions/UpdateReservation/index.handler
    events:
      - httpApi:
          path: /reservation
          method: PATCH

resources:
  Resources:
    roomsDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: room-db
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
